### ISSUE TITLE
[Feature]: Regarding "malicious" apps

### ISSUE THREAD

**Issue by d9j** [PlayCover/PlayCover#1160]
### Is your feature request related to a problem?

the thing about malicious apps
https://docs.playcover.io/miscellaneous/blocked_apps

### Describe the solution you'd like

I see it's possible maybe consider allow them to run it in the virtualized environment  with custom configuration of permissions to prevent malicious behavior . Im not certain how to implement it. but since apple provides virtualization framework  . and there are solutions available like qemu . which may make it easier to implement 

### Anything else?

nope

### Issue Language

- [X] Yes my issue is written in English

**Comment by zanderp25** [comment]
Apple's Virtualization framework is made to virtualize (as in a virtual machine) macOS or Linux instance, not iOS. Virtualizing iOS would defeat the entire purpose of this app: to run iOS apps _natively_. You can use something like UTM to virtualize a macOS instance but that won't help you run the iOS apps. You _can_ run the iOS app in there via PlayCover, though, because that is isolated from the host computer, but you would have to modify the PlayCover app to allow that app to be run.

Edit: Also, I'm not sure if or how well PlayCover and/or the app would run inside a virtual machine.
