### ISSUE TITLE
[Game Support]: How to update ur genshin without redownloading ke IPA file? 

### ISSUE THREAD

**Issue by nueeer** [PlayCover/PlayCover#1415]
### App Store link

https://apps.apple.com/id/app/genshin-impact-v4-5/id1517783697

### Current issues

- [X] Game fails to install
- [ ] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

How to update ur genshin without redownloading ke IPA file? Can that be done inside of playcover or should i started the whole thing from the start?

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by notsharuu** [comment]
same issue here!

**Comment by aitlinoa** [comment]
I tried to add it to my ipa library and connect with playcover but it wouldnt download because it cant extract the file, and deleting old version aint cutting it
<img width="619" alt="Screenshot 2024-03-15 at 1 51 44 PM" src="https://github.com/PlayCover/PlayCover/assets/148207124/34bcdd26-42bf-4de8-9d29-655eaff81981">

**Comment by yrmuq** [comment]
@aitlinoa  same problem, only way is just delete old version and download and install new version

**Comment by TheMoonThatRises** [comment]
You need the redownload the IPA file to update Genshin Impact.
