### ISSUE TITLE
[Bug]: Genshin quitting upon opening wishing page

### ISSUE THREAD

**Issue by henoche** [PlayCover/PlayCover#1494]
### Describe the bug

Genshin Impact, played via PlayCover, will quit upon opening the wishing page with graphic settings of a resolution scaler higher than 2.4, as shown in the image below:
<img width="1012" alt="Screenshot 2024-05-27 at 17 54 04" src="https://github.com/PlayCover/PlayCover/assets/125202381/b06c09f6-d187-419e-8bf3-0b8f8f051651">
This occurs when gameplay is perfect, which really doubts player whether they've made a mistake during installation, possibly resulting in the re-installation of games ~(totally did not happen to me)~

### Steps to reproduce

device: m2 pro macbook pro
macOS: Sonoma 14.5
genshin version: 4.7
playcover: 3.0.0 beta 2

Genshin Impact internal settings were tuned to the highest possible within the app (shouldn't alter the bug)
Genshin Impact PlayCover setting are shown as below:
<img width="1012" alt="Screenshot 2024-05-27 at 17 54 04" src="https://github.com/PlayCover/PlayCover/assets/125202381/e495aaa5-7674-4aa6-832b-5e2d1302dde6">
note: iOS device is iPad Pro (12.9 inch) (6th gen) M2 | 8gb 

**the game will crash with resolution scaler of 2.4 or above when opening wishing site**

### Expected behaviour

1. this crash is unexpected as PlayCover does not show the _'high resolution may cause crashing'_ warning
2. it is also unexpected as the game is perfect to play apart from opening the wishing site

### What version of PlayCover are you using?

3.0.0 beta 2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by MEMORIEmusic** [comment]
2D UI Elements in Genshin have a hard time rendering at high resolutions. the "High resolution may cause crashing" warning does not show because the resolution itself is not high, its the scaler.

There's little to no point playing it on anything above 2.0 scaling. The best you can get with your display is Auto(based on display) with 2.0 resolution scaling.

**Comment by henoche** [comment]
Great, thank you very much
So what does the scaling do?
Wish you a good day!

**Comment by MEMORIEmusic** [comment]
> Great, thank you very much So what does the scaling do? Wish you a good day!
> […](#)

macOS renders things in a way different than Windows. that's cuz Mac screens are super-high DPI retina displays(for context: a normal 4K monitor would be 110 DPI, an apple one would be 220 DPI). 

what it essentially does is renders everything at 2 times the resolution of your display then shrink it down - in order to achieve that 220 DPI. That's why Mac displays are so sharp and clear. it is also why apple's studio display and pro display xdr have weird resolutions - 5K and 6K respectively.

in PlayCover, the resolution scalar decides this. at 2.0 resolution scalar and 1080p, you're essentially running the game at 4K and then shrinking it down to 1080p. I guess you can see how its going - 1080p and 2.4 times resolution scalar is essentially rendering the game at 4.6K and then shrinking it down to 1080p. the 2D aspects of the game have trouble handling this high resolution(because lets be real, no phone has a 4.6K display) and so it crashes.

**Comment by henoche** [comment]
Thanks for this support. Amazing!
