### ISSUE TITLE
[Game Support]: Nikke

### ISSUE THREAD

**Issue by lnatpunblhna** [PlayCover/PlayCover#1608]
### App Store link

https://apps.apple.com/us/app/goddess-of-victory-nikke/id1585915174

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [X] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Unable to run the game. When launching the game, there is no image displayed, only the dock icon. The game runs normally after uninstalling Play Tools.

### What version of PlayCover are you using?

3.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by notjl** [comment]
There are two ways you can play Nikke:

1.  You can remove `PlayTools`. No worries about keymaps since if you've played the PC client before, it has same keybinding as that one. (Although, Shift [Auto Aim] toggle doesn't work)
2. Set your `Resolution` to `App Default` and tick the `Fix window display issues` and set it to `Alternate`

For my preference, I would choose the former since you can have the horizontal gameplay, you'd get more view of the battle area. Since the latter has a problem with setting the game to Horizontal.

**Comment by lnatpunblhna** [comment]
> 您可以通过两种方式玩 Nikke：
> 
> 1. 您可以删除 .不用担心键盘映射，因为如果您以前玩过 PC 客户端，它具有与那个相同的键绑定。（虽然 Shift [自动瞄准] 切换不起作用）`PlayTools`
> 2. 将您的设置为并勾选并将其设置为`Resolution``App Default``Fix window display issues``Alternate`
> 
> 根据我的喜好，我会选择前者，因为你可以有水平游戏玩法，你会获得更多的战斗区域视野。由于后者在将游戏设置为水平时存在问题。

**Comment by ic358e** [comment]
> There are two ways you can play Nikke:
> 
> 1. You can remove `PlayTools`. No worries about keymaps since if you've played the PC client before, it has same keybinding as that one. (Although, Shift [Auto Aim] toggle doesn't work)
> 2. Set your `Resolution` to `App Default` and tick the `Fix window display issues` and set it to `Alternate`
> 
> For my preference, I would choose the former since you can have the horizontal gameplay, you'd get more view of the battle area. Since the latter has a problem with setting the game to Horizontal.

I tried this, but after NIKKE opens, it shows the shiftup logo, and then it just becomes a blackscreen
