### ISSUE TITLE
[Bug]: Azur Lane not opening

### ISSUE THREAD

**Issue by existence333** [PlayCover/PlayCover#1703]
### Describe the bug

The game doesn't open properly; trying to open the app results in it flashing across the screen then closing. MIght have something to do with the ipa, since the issue started after downloading the new ipa, but I'm not sure.

### Steps to reproduce

Trying to open the app results in this issue.

### Expected behaviour

The app opens normally.

### Crash log

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               AzurLane [45460]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/*/com.YoStarEN.AzurLane.app/AzurLane
Identifier:            com.YoStarEN.AzurLane
Version:               8.2.1 (2024091901)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-09-28 15:27:32.3336 -0700
OS Version:            macOS 14.3.1 (23D60)
Report Version:        12
Anonymous UUID:        D420FC34-1881-4F60-CF9C-F53744235926

Sleep/Wake UUID:       CE18E580-29A6-4C41-AE2F-953135AEC68E

Time Awake Since Boot: 300000 seconds
Time Since Wake:       3892 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000188cbb33c

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [45460]
```

### What version of PlayCover are you using?

3.1.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by yufanho** [comment]
Same issue here for JP version. Local env is Sonoma 14.5 with M2 chip.

**Comment by Coconinja25** [comment]
Same issue here.  Local env is Sonoma 14.5 with M1 chip

**Comment by david-christian** [comment]
me too has same issue. 
M1 sonoma 14.5 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               ProductName [20527]
Path:                  /Users/USER/Library/Containers/io.playcover.PlayCover/*/com.YoStarJP.AzurLane.app/ProductName
Identifier:            com.YoStarJP.AzurLane
Version:               8.2.14 (2024091801)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-10-01 21:30:04.0001 +0800
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        6F7C7607-2CFE-39A1-6B2E-A698C8D1AA74

Sleep/Wake UUID:       CF2E0C19-475C-44E3-AE65-C19771DE227E

Time Awake Since Boot: 810000 seconds
Time Since Wake:       78432 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   ProductName [20527]

Application Specific Information:
abort() called

**Comment by Coconinja25** [comment]
Guys I updated to macOs sequoia and now it works
