### ISSUE TITLE
[Genshin] 3D quality does not change when the resolution is changed.

### ISSUE THREAD

**Issue by tellus1019** [PlayCover/PlayCover#179]
![resolution](https://user-images.githubusercontent.com/25951129/185434916-f67b85b5-1dff-45d7-9525-78b57dbe97d1.jpg)

Resolution changes were investigated using PlayCover 1.1.0.

Genshin's window size does indeed increase, but the quality of the in-game representation does not change from 1080p.
Comparison images are provided (taken at the same location and with the same settings)

At a quick glance, 1080p looks better (e.g., faces), but if you look at things like feet, you can see that there is no difference in quality.
However, the increased resolution places a greater load on the machine.
I checked the GPU utilization on the M1 and it was about 80% utilization at 1440p compared to about 60% at 1080p.

Currently, there is little reason to choose 1080p or higher on Genshin.
I don't know if it is possible to change the internal rendering resolution, but there is no return on the increased load.
Please investigate if this can be improved.

**Comment by IsaacMarovitz** [comment]
If you look at the smoothness of the aliasing between the two images, there is a slight quality difference, which is much more perceptible on UI and large open scenes. 

About the quality of the models and textures themselves, there is nothing we can do to change that. Genshin Impact for iOS is not designed for Macs, and therefore the resources it downloads are significantly lower quality than the ones on PC. Because these resources are locked to specific builds of the game, there is no way for us to change them from within PlayCover. We cannot swap models and textures either without tripping Hoyoverse's integrity check.

The GPU utilisation is increasing because the game is running at a higher res. Higher res = more resources to render.
