### ISSUE TITLE
[Feature]: Support Multi-touch Touchpad mapping on screen

### ISSUE THREAD

**Issue by EigenTom** [PlayCover/PlayCover#244]
### Is your feature request related to a problem?

Hi, I'm asking if it's possible to implement multi-touch touchpad mapping support to the tool. It would be helpful in specific circumstances where simple key mappings wouldn't be helpful for playing the game which require intensive touch /drag interactions or multi-touch actions, such as SmashHit, The ROOM or other prevalent Rhythm Games like Arcaea or Project Sekai.

### Describe the solution you'd like

One possible solution I found is to use an app `Inklet`, which was meant to be a tool transferring the touchpad into a digitiser. It will intercept touch events of the touchpad and create a mapping from the touchpad to the screen. The official site is:

https://tenonedesign.com/inklet.php

However, the event it emulate is "mouse cursor moving" and "clicking", therefore lacking proper multi-touch support.

### Anything else?

The demonstration of how it would work is: https://www.youtube.com/watch?v=sdNpbMbq90Q

### Issue Language

- [X] Yes my issue is written in English

**Comment by JoseMoreville** [comment]
This is planned in a future, but there's no ETA

**Comment by nixtoshi** [comment]
I found I could use multi-touch for stuff like zooming in with 2 fingers, rotating a 3D model, or dragging stuff with 3 fingers on an app using the macbook's trackpad by simply ALT-tabbing to the game or iOS app, instead of clicking on it.

So:
1. Open app on PlayCover
2. Command tab out of it
3. Command tab again to return

Done. Multi-touch from trackpad working (at least on a game I tried).

I don't know why this works. When I click on the opened iOS app from my dock the trackpad doesn't work inside the app
