### ISSUE TITLE
Search update feature issues

### ISSUE THREAD

**Issue by Depal1** [PlayCover/PlayCover#36]
The search update feature on PlayCover is triggering on Github pre-releases. Is this expected behavior?

On another note, it is directing to a .zip instead of the currently used .dmg.

Example: it is directing to https://github.com/PlayCover/PlayCover/releases/download/1.0.7/PlayCover.1.0.7.zip

instead of https://github.com/PlayCover/PlayCover/releases/download/1.0.7/PlayCover_1.0.7.dmg

**Comment by ohaiibuzzle** [comment]
From what I can tell, the update code doesn't really do any checking of whether or not the release is a pre-release.
And it is indeed hardcoded to `.zip` instead of `.dmg` as seen [here](https://github.com/PlayCover/PlayCover/blob/cd0ad23df968be421fbfebda879e37bd59418644/PlayCover/Services/UpdateService.swift#L42)
