### ISSUE TITLE
[Feature]: Intel support

### ISSUE THREAD

**Issue by baptx** [PlayCover/PlayCover#434]
### Is your feature request related to a problem?

The original PlayCover project said "Intel macs support will be implemented later." like we can see in the commit history: https://github.com/PlayCover/PlayCover/tree/265cee37027d8956f4739040cf8b3da4e32685ff
Is it still planned to add Intel support and what is the technical work that needs to be done? I guess it will require ARM translation with a library like it is done on Android with libhoudini. Intel support would also be nice for Linux and Windows users if it is possible to run macOS with iOS apps on VirtualBox for example.

This GitHub project says "If you have an Intel Mac, you can explore alternatives like Bootcamp or emulators.".
What do you mean by Bootcamp? I did not find any information and for emulators, I read they don't exist for iOS, there are just simulators where you need to have the source code of an iOS app to make it compatible on macOS using an Intel processor.

By the way, is it possible to run iOS apps from the IPA file on the cloud with Apple silicon M1 as-a-Service (https://scaleway.com/en/hello-m1/)? If someone has tried, it could be useful to share the experience and maybe mention the alternative in the README for Intel users.

### Describe the solution you'd like

See above.

### Anything else?

No

### Issue Language

- [x] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
No. PlayCover leverages the existing Catalyst infrastructure on M1 Macs, which had been beefed up with implementations for most if not all iOS frameworks to run the arm64 slices of your apps on the Mac without changes. This is the exact same strategy Apple has for their iOS apps runtime, hence why we can achieve very high performance on most apps (since nothing at all needs to be simulated)

This infrastructure simply does not exist on Intel Macs, and even if they do, you need x86_64 builds of iOS apps to leverage it. Apple itself doesn't provide "backward" Rosetta should be an indication that this won't be happening any time soon

TL,DR: WONTFIX, NOISSUE

**Comment by ZhichGaming** [comment]
Intel support is not planned and has been removed from the planning board. It was only added because there was speculation about running apps on the T2 chip, but that is not possible. Bootcamp is an app on intel macs where you run windows, but it is not supported on ARM macs. I don't think that there is any simulators for iOS except the Xcode one where you test your apps.
