### ISSUE TITLE
[App Support]: Hotstar that used to work previously now not letting me login

### ISSUE THREAD

**Issue by singhalrishi27** [PlayCover/PlayCover#518]
### App Store link

https://apps.apple.com/in/app/hotstar-live-cricket-movies/id934459219

### Current issues

- [ ] App fails to install
- [ ] App fails to open
- [ ] App crashes randomly during usage
- [ ] App experiences graphical issues or broken UI
- [ ] App fails to connect to servers
- [X] Other

### More details

App wont let you login

### Issue Language

- [X] Yes my issue is written in English

**Comment by meghrathod** [comment]
Any fixes?

**Comment by singhalrishi27** [comment]
> Any fixes?

Use appdb its a lot better than play cover instagram works too google photos as well

**Comment by ohaiibuzzle** [comment]
> Any fixes?

You can test it in Nightly with PlayChain and see if it works there (you will need some basic troubleshooting). Logins in apps are pretty finicky due to how PlayCover works (not tying you to any third party signing services)

**Comment by ohaiibuzzle** [comment]
> Use appdb its a lot better than play cover instagram works too google photos as well

@singhalrishi27  Well, true. Apps work better when they are signed using an Apple Developer ID certs (Sideloadly and AppDB uses this).
However with AppDB you are practically installing an MDM profile onto your device which allows them to potentially do other things on your device. They may disclose it on installation but there is nothing that stops them from doing other things as you already approved the profile. Some people would rather use PC or Sideloadly instead of tying to those

PlayCover's approach is fully on-device and open for anyone to audit. It may requires more tweaking, but is a lot more transparent in what it is doing

**Comment by singhalrishi27** [comment]
> > Use appdb its a lot better than play cover instagram works too google photos as well
> 
> @singhalrishi27 Well, true. Apps work better when they are signed using an Apple Developer ID certs (Sideloadly and AppDB uses this). However with AppDB you are practically installing an MDM profile onto your device which allows them to potentially do other things on your device. They may disclose it on installation but there is nothing that stops them from doing other things as you already approved the profile. Some people would rather use PC or Sideloadly instead of tying to those
> 
> PlayCover's approach is fully on-device and open for anyone to audit. It may requires more tweaking, but is a lot more transparent in what it is doing

I should have mentioned it before there is always some risk upon Side-loading and we don’t know appdb well  also they are based on china i just use discord, I don’t know to trust them or not i never heard them doing some sketchy

**Comment by meghrathod** [comment]
EDIT: I can login with with SIP turned off, insecure but while I'm flying and need downloads that would be least of my problems, hope this helps others
