### ISSUE TITLE
[Bug]: Resolution has been lowered with 2.0.4.

### ISSUE THREAD

**Issue by Nipol** [PlayCover/PlayCover#744]
### Describe the bug

Updated Ventura 13.2 and updated 2.0.4.
After that, the screen size of the genshin impact remains the same, but the resolution inside the game decreases, so the pixels stand out.
It looks like a small screen is zoomed in to a big screen.

There is another problem.
If the resolution is selected as `Default`, the screen problem in 2.0.3 will be reproduced as it is.

### Steps to reproduce

Ventura 13.2 with 2.0.4.

### Expected behaviour

I'm using a QHD display, and the resolution is generally clean.

### Crash log

```shell
No Crash
```

### What version of PlayCover are you using?

2.0.4

### What version of macOS are you using?

Ventura (macOS 13.2)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ohaiibuzzle** [comment]
Actually no, it has always kind of been like that. Think of the resolution inside PlayCover be more like an display output resolution. Genshin also have an internal render resolution that it uses (something 900p for M1 I think, because even though these are powerful ARM chips, their GPU aren't good enough to run at full native res). That is dynamically determined by the game based on device and processor on iOS

Playing around with the output resolution settings may help, but yeah you won't be running full res on these devices

**Comment by IsaacMarovitz** [comment]
App Default is not intended to be used in games. Please use Auto, Custom, or one of the Presets.

**Comment by Nipol** [comment]
Check this!
Both are 1440p, set at 16:10 ratio, but have different internally processed resolutions.


Ventura 13.1 with 2.0.3
![스크린샷 2023-01-25 오전 10 40 50](https://user-images.githubusercontent.com/693461/214461913-5834384b-6bef-4635-b809-2bae6d8f96c3.png)

Ventura 13.2. with 2.0.4
![스크린샷 2023-01-25 오전 10 39 25](https://user-images.githubusercontent.com/693461/214461956-91763342-1abc-465f-9d55-6c5e84f01966.png)
