### ISSUE TITLE
[Game Support]: Honor Of King

### ISSUE THREAD

**Issue by Ducmanhvn** [PlayCover/PlayCover#949]
### App Store link

https://apps.apple.com/br/app/honor-of-kings/id1619254071?l=en

### Current issues

- [ ] Game fails to install
- [X] Game fails to open
- [ ] Game crashes randomly during gameplay
- [ ] Game does not work with keymapping
- [ ] Game experiences graphical issues or broken UI
- [ ] Game fails to connect to servers or complete download

### More details

Black Screen When Open

### Issue Language

- [X] Yes my issue is written in English

**Comment by TheMoonThatRises** [comment]
This issue can be fixed by opening the app in Finder and renaming it to something without spaces (i.e. `hok.app` or `honorofkings.app`). You can find it by left clicking the app in PlayCover and clicking `Show in Finder`. I suspect this may be similar to #668. If this doesn't fix it you can reopen this issue.

**Comment by Ducmanhvn** [comment]
thanks work smoth
