### ISSUE TITLE
[Bug]: Mouse fails to move screen (camera) in games suddenly, hitting 'option' twice would make it work

### ISSUE THREAD

**Issue by fayiz-jr** [PlayCover/PlayCover#964]
### Describe the bug

i have been facing this issue for a few months now, where the mouse would stop moving the screen mostly after teleporting in genshin impact for example, and sometimes suddenly while playing and i need to hit "option" to re-enable the keymap and it'd work again, and sometimes it works again on its own, i tried everything, wiped my macbook air m1 and installed the game from scratch and it's still present, and trying every possible new version of playcover and nightly mostly and it's still happening...it's really annoying especiallywhen i'm in combat:")... i will include a video link for the problem, you'd notice how fast i'm moving the mouse once the keymap for it works again on its own. idrk coding, if u need more info that i can provide please do ask and instruct me on how to get such info... thank you all! you're lives' savers! [https://drive.google.com/file/d/1EOGuTWa6k56XmwLJRM0O0I6SfXwW1U80/view?usp=sharing] (url)

### Steps to reproduce

mouse keymap stops working and stops moving the screen (camera)

### Expected behaviour

the mouse to keep working as it used to do a few months ago😅

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Ventura (macOS 13)

### Issue Language

- [X] Yes my issue is written in English

**Comment by XuYicong** [comment]
I'm sad to tell you that this issue is long known and very hard to solve. First of all, everything works correctly, nothing goes wrong. The reason this happens is that, playcover tends to keep the touch point longer after you stop moving your mouse, to avoid the dead zone of start dragging the screen. This is crucial to precise operations, like aiming with a bow. Otherwise it would be impossible to aim at small objects at a distance.

When you teleport, the game would enter a teleport screen. If you move your mouse in this screen, when teleport completes and you move your mouse, the game would think you're still moving in that teleporting screen.

There are easier ways to avoid this problem. Just stop moving your mouse in teleporting screen and character's ult cutscene. Even when you meet this, their are easier ways to get it back. You don't need to press option twice, just wait for half a second (not moving your mouse) and it could function again.

**Comment by fayiz-jr** [comment]
oh okay thank you for explaining that... i hope you get to fix it in the future, rooting for y'all...
