### ISSUE TITLE
[Game Support]:  Can not open the game ? 

### ISSUE THREAD

**Issue by thonguyenus** [PlayCover/PlayCover#991]

**Comment by ndtho22APCS** [comment]
I fixed it!

**Comment by JinchuanL** [comment]
Hi,

Can you provide more details such as which game/app and your device?

**Comment by falgun-stack** [comment]
Hello Andy,

Thanks for your reply,
You guys are really awesome but when i run pubg it gets banned so how can i
fix it?

Should i need to write some code in swift?

Thank you

**Comment by JinchuanL** [comment]
It is because PUBG is not allowed to play by using PlayCover.

You can have a look at these PlayCover Offical Docs:
https://docs.playcover.io/miscellaneous/blocked_apps#blocked-games

**Comment by falgun-stack** [comment]
Thanks for your instant reply,

But still i want to play that game so what can i do?

**Comment by JinchuanL** [comment]
I am not sure, but obviously PlayCover does not support this game.

From the PUBG end, it may be unfair for players. Think about some players playing it using fingers to drag and move and some players using a keyboard and mouse. We all know it is faster and more accurate by using a keyboard and mouse than fingers in a FPS game. That is probably why PUBG Mobile does not allow you to play it on a Mac.

Maybe you can try other software or just play the PUBG desktop version instead of the mobile version.

I hope this helps.

**Comment by falgun-stack** [comment]
I understand but do you have any solutions like alternative options?
